### ISSUE TITLE
Very slight cosmetic request

### ISSUE THREAD

**Issue by jonheal** [thomassidor/tinytricks#12]
I have a very slight cosmetic request, Thomas. Either slightly enlarge or slightly reduce the size of the red circle behind the top jack(s) so that it centers better the jack(s). Right now, it protrudes a bit to the top-left.

Good work!

**Comment by thomassidor** [comment]
Hi Jon

Yeah, that have been bothering me for a while as well, but never got to fix it. I'll make sure to fix it with the next release.

Thanks! :)
