### ISSUE TITLE
Small Issues

### ISSUE THREAD

**Issue by pgatt** [thomassidor/tinytricks#2]
Hi Thomas, I think your make file should read:

RACK_DIR ?= ../..

rather than RACK_DIR ?= ..\..

In the plugin browser module description MG8 is missing an M - it reads Tiny Tricks odulation Generator x8. Small thing, but I just noticed it.

Love the look and functionality of the modules by the way.

Hope you don't mind me having a play with the modules.

**Comment by thomassidor** [comment]
Hi

Thanks for the feedback - very much appreciated! And of course you're more than welcome to play around with them - that's what they're here for :)

I've added the fixes to the dev branch for 1.1.0 which I'll soon merge into the master.

In 1.1.0 there's also a few variations on oscillators. Feel free to have a look at those too.

**Comment by ContemporaryInsanity** [comment]
Hi Thomas.

You have RACK_DIR ?= ..\\.. which won't build on linux.

**Comment by ContemporaryInsanity** [comment]
Hmmm, the back slash disappeared for some reason.  Anyway, .. forward slash ..

**Comment by thomassidor** [comment]
@ContemporaryInsanity - Got it, thanks :) Fixed it in the dev branch (for v1.1.0). Will soon merge it into master.

**Comment by thomassidor** [comment]
Just merged the changes into master and release v1.1.0, so closing this.
