### ISSUE TITLE
Failure to get Working v2

### ISSUE THREAD

**Issue by hardyfinn** [thomassidor/tinytricks#23]
Apologies. I've tried and failed to get this working in rack v2. RM8 is such a great module for my drum channels.
I have tried putting the SRC zip into the v2 plug ins folder. I've tried expanding it. I haven't seen a .vcvplugin file though.
Any help gratefully received.

**Comment by hardyfinn** [comment]
On reflection, i do not see a full release for v2.5, only the source. Please add a full windows release zip file when you can.

**Comment by netboy3** [comment]
Attached is a zip with binary builds for commit  567c70ccef86789ec2f3e7331a83930819ee25e2 V2 as of this time on all three platforms. Make sure to unzip before installing. Only briefly tested on Linux, but they built cleanly on all platforms.

[TinyTricks-2.5.0.zip](https://github.com/thomassidor/tinytricks/files/7654686/TinyTricks-2.5.0.zip)

**Comment by hardyfinn** [comment]
Thank you kindly. Works on Windows. Time to create my magnum opus!
