### ISSUE TITLE
Simplex Oscillator crashed on linux

### ISSUE THREAD

**Issue by docb** [thomassidor/tinytricks#26]
567c70ccef86789ec2f3e7331a83930819ee25e2 with rack 2.0.4 linux ubuntu jack2
Steps: 
add Simplex Oscillator on an empty patch.
quit
start rack again
==> segmentation fault
gdb says: seg fault in line 195
`scope->addFrame(value);`
this seems to be caused by scope == NULL (as it works when i add a check)
this leads to an interesting issue: the scope is made in the widget code. so then it seems that the module
may be running before the widget is created?

**Comment by baconpaul** [comment]
This is fixed in d95b6cece8e57fbf2aa0eadb33ab5c7f32a31868 and we are working on getting it to the library.
