### ISSUE TITLE
Random Wrangler crashes Rack when adding module

### ISSUE THREAD

**Issue by alefnull** [thomassidor/tinytricks#27]
platform: windows 11
rack version: 2.0.4
latest library version of the plugin

opening the module browser and attempting to drag Random Rangler into my rack immediately causes the application to crash to desktop. Wrangler seems to be the only problematic module.

**Comment by DanGarman** [comment]
Same for me with Rack 2.0.6 with Windows 10 Home.

**Comment by cosmoproductions** [comment]
Adding the stack trace from log.txt.  100% repro whether the rack is empty or not.  Windows 10, VCV Pro 2.1.2
Thanks for looking into it!

[9.930 info src/app/Browser.cpp:90 chooseModel] Creating module Tiny Tricks Random Wrangler
[10.353 fatal adapters/standalone.cpp:48 fatalSignalHandler] Fatal signal 22. Stack trace:
36:  0x0
35: raise 0x7ffa1956abe0
34: abort 0x7ffa1956f1e0
33: ZN9TTLWidgetD1Ev 0x7ff9a7869f20
32: ZN10WAVEWidgetD1Ev 0x7ff9a783a7a0
31: ZSt7shuffleIN9__gnu_cxx17__normal_iteratorIPiSt6vectorIiSaIiEEEERSt26linear_congruential_engineIjLj16807ELj0ELj2147483647EEEvT_SA_OT0_ 0x7ff9a78c1610
30: ZZN4rack11createModelI9RM8Stereo15RM8StereoWidgetEEPNS_6plugin5ModelENSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEEN6TModelD1Ev 0x7ff9a78ce3a0
29: ZZN4rack11createModelI9RM8Stereo15RM8StereoWidgetEEPNS_6plugin5ModelENSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEEN6TModelD1Ev 0x7ff9a78ce3a0
28: ZNSt6vectorIiSaIiEE17_M_realloc_insertIJiEEEvN9__gnu_cxx17__normal_iteratorIPiS1_EEDpOT_ 0x7ff9a78b60a0
27: ZN14RANDOMWRANGLERC1Ev 0x7ff9a7846560
26: ZZN4rack11createModelI14RANDOMWRANGLER20RANDOMWRANGLERWidgetEEPNS_6plugin5ModelENSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEEN6TModel12createModuleEv 0x7ff9a78c6e20
25: ZN4rack3app11AudioButton8onActionERKNS_6widget6Widget11ActionEventE 0x7ff9d242db30
24: ZN4rack3app7browser8ModelBox8onButtonERKNS_6widget6Widget11ButtonEventE 0x7ff9d28d06e0
23: ZN4rack6widget6Widget8onButtonERKNS1_11ButtonEventE 0x7ff9d28fa910
22: ZN4rack6widget6Widget8onButtonERKNS1_11ButtonEventE 0x7ff9d28fa910
21: ZN4rack6widget6Widget8onButtonERKNS1_11ButtonEventE 0x7ff9d28fa910
20: ZN4rack2ui12ScrollWidget8onButtonERKNS_6widget6Widget11ButtonEventE 0x7ff9d24708a0
19: ZN4rack3app7browser7Browser8onButtonERKNS_6widget6Widget11ButtonEventE 0x7ff9d28ce660
18: ZN4rack2ui11MenuOverlay8onButtonERKNS_6widget6Widget11ButtonEventE 0x7ff9d246f8d0
17: ZN4rack6widget12OpaqueWidget8onButtonERKNS0_6Widget11ButtonEventE 0x7ff9d28f9bc0
16: ZN4rack6widget10EventState12handleButtonENS_4math3VecEiii 0x7ff9d2474a10
15: ZN4rack6window3Svg4loadERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE 0x7ff9d2479860
14: glfwGetWin32Monitor 0x7ff9d24bb910
13: CallWindowProcW 0x7ffa196fe460
12: CallWindowProcW 0x7ffa196fe460
11: glPushClientAttrib 0x7ff9fc90a8d0
10: CallWindowProcW 0x7ffa196fe460
9: DispatchMessageW 0x7ffa196fe040
8: glfwPollEventsWin32 0x7ff9d24bfb40
7: ZN4rack6window6Window4stepEv 0x7ff9d247ad60
6: ZN4rack6window6Window3runEv 0x7ff9d247b720
5: ZN4rack6window6Window3runEv 0x7ff9d247b720
4: ZN4rack6window6Window3runEv 0x7ff9d247b720
3: ZN4rack6window6Window3runEv 0x7ff9d247b720
2: ZN4rack6window6Window3runEv 0x7ff9d247b720
1: BaseThreadInitThunk 0x7ffa19c07020
0: RtlUserThreadStart 0x7ffa1b402630

**Comment by overlobe** [comment]
sorry I didn't see this. Having similar issue with duplicating RW. And opening a patch that has more than one instance of RW in it. [POsted issue here](https://github.com/thomassidor/tinytricks/issues/31)

OSX M2 chip macBook Air

**Comment by baconpaul** [comment]
Fixed in [9e84661](https://github.com/thomassidor/tinytricks/commit/9e8466188a5ea2aab645a3c362349516c977a3a6)
 ·

we are working on getting it to the library
