### ISSUE TITLE
Simplex Oscillator Crash on startup  (Win 10)

### ISSUE THREAD

**Issue by Outboarder** [thomassidor/tinytricks#29]
I made a patch using Simplex Oscillator and saved. after loading VCV crashed, I removed Simplex Oscillator from Rack library, now patch loads without crash.
Here is the faulty patch:
https://www.dropbox.com/s/1gw9b9rayl3fr64/crash.vcv?dl=0

**Comment by Outboarder** [comment]
I think it's GUI bug not the DSP. when I change the skin to Cod gray and save. it will broke the patch 7 out of 10 times. 
hard to replicate, hope for a fix.

**Comment by baconpaul** [comment]
This is fixed in d95b6cece8e57fbf2aa0eadb33ab5c7f32a31868 and we are working on getting it to the library.
