### ISSUE TITLE
RW duplicate crash

### ISSUE THREAD

**Issue by overlobe** [thomassidor/tinytricks#31]
Hi there, I think I might of found a bug in the random Wrangler module. I love it by the way it's really cool thank you for making it and thank you for making it available!
The bug seems to be when I want to duplicate it, it crashes VCV rack. I am using Version 2.3.0 of vcv rack, and I am pretty sure I'm using the latest version of your module. Let me check: yep latest version.
The crash appears to happen when I duplicate the random Wrangler module, and VCV logs don't seem to write anything beyond the point of creating the first instance of the module. This also seems to have a problem when I have saved a patch that has two copies of the same module in it (eg: random Wrangler modules) 
I can make the patch. I can run the patch. I can save the patch, but when I try to open it, VCV crashes, so it seems to be that it's doing the same sort of thing here, in creating this instance of the module and then crashing. Again, the logs don't show me anything from this, sorry.

Thanks again for making such a cool modules, really liking them and feel free to reach out if there's anything else I can help with cheers!

**Comment by overlobe** [comment]
OSX M2 chip macBook Air - macOS 13.3.1

**Comment by baconpaul** [comment]
Fixed in [9e84661](https://github.com/thomassidor/tinytricks/commit/9e8466188a5ea2aab645a3c362349516c977a3a6)
 ·

we are working on getting it to the library
