### ISSUE TITLE
Tiny Tricks - Random Wrangler

### ISSUE THREAD

**Issue by cummimgs606** [thomassidor/tinytricks#34]
Hello Thomas,

I love your modules and find them very useful. I am having an issue with the Random Wrangler, I am able to place this module into my VCV grid but when I save and open the project it crashes the VCV app.

The error Report is;
**Rack crashed during the last session, possibly due to a buggy module in your patch. Clear your patch and start over?**

It works perfectly in Rack-1 VCV, but crashes Rack-2 VCV. All the other Tiny-Tricks modules work perfectly fine and can save them in my project and open them in Rack-2 VCV with expected result.

I am using Rack2 on a Apple M1 Max, running MAC OS 13.3.1 Ventura.

I hope you can resolve this issue; because these modules are great.

Kind Regards Mark

![Screenshot 2023-11-29 at 13 23 48](https://github.com/thomassidor/tinytricks/assets/2545726/6e6639f0-b6e7-406f-9ec6-dfd85ec9777a)
![Screenshot 2023-11-29 at 13 23 58](https://github.com/thomassidor/tinytricks/assets/2545726/4d8f9a6d-95f2-4679-a623-e2358fd233ff)
![Screenshot 2023-11-29 at 13 34 16](https://github.com/thomassidor/tinytricks/assets/2545726/3d5837e1-e7a2-4211-8ea6-bd365ceb07fb)

**Comment by baconpaul** [comment]
Fixed in [9e84661](https://github.com/thomassidor/tinytricks/commit/9e8466188a5ea2aab645a3c362349516c977a3a6)
 ·

we are working on getting it to the library
