### ISSUE TITLE
RM8Base.svg missing or not needed ?

### ISSUE THREAD

**Issue by Petervos2018** [thomassidor/tinytricks#4]
Love your set of modules, however...

I think there are reverences to RM8Base.svg in your modules. But the svg is not in the res/panels folder.

[3.855 warn src/window.cpp:75] Failed to load SVG C:\Users\Me\DOCUME~1/Rack/plugins-v1/TinyTricks/res/panels/RM8Base.svg

VCV gives warnings in the log file.

I'm no programmer, do with this info what you want.

Greetings Peter

**Comment by thomassidor** [comment]
Hi Peter

Thanks a lot for the report!

It shouldn't do anything in terms of the functionality, but it makes sense to fix it to remove that warning. Scheduled for v1.1.1 together with a few other things.

Do let me know if you find anything else - or if you have suggestions :)

**Comment by thomassidor** [comment]
Fixed in v1.1.1 that has just been released. Just waiting for new build to be included in VCV Plugin Library. Closing this.
