### ISSUE TITLE
Tiny Trick Logic output too low max 1V

### ISSUE THREAD

**Issue by Petervos2018** [thomassidor/tinytricks#6]
I tried some gates but the max output was just 1V max ?

![TinyBool-21102019](https://user-images.githubusercontent.com/46076474/67241436-bc4aea80-f453-11e9-8e28-5d7c3f7afdc4.png)

**Comment by thomassidor** [comment]
You're right - it should be 10V. I'll fix it with the next release.

Thanks!

**Comment by thomassidor** [comment]
Just released the fix as part of v1.2.0.

Waiting for updated module to be pulled to VCV library.

Closing ticket.
