### ISSUE TITLE
simplex noise oh yes

### ISSUE THREAD

**Issue by glocke01** [thomassidor/tinytricks#8]
Hey, your readme says you're happy to receive requests in issues, so, can I just say, I am super excited about a simplex noise module. I really like pitched noise and smooth random stuff, so this would be very useful to me!

**Comment by thomassidor** [comment]
Hey

I just added the Simplex Noise LFO in the previous release (still waiting to be included in the VCV Library build - but should be anytime now). And I'm working on a Simplex Noise based Oscillator.

Could you elaborate a bit more on what you need and what you mean by "pitched noise" - then I'll gladly create it :)

**Comment by glocke01** [comment]
I mean "pitched noise" in a sort of general way. Any sort of clocked noise is "pitched." AFAIK, simplex puts zeroes at regular intervals, which means it is a sort of pitched noise. So, I'm just offering my encouragement to get PN1 into the library. 

A similar idea would be smoothed S&H noise a la http://doc.sccode.org/Classes/LFBrownNoise2.html 

(I am into modal/waveguide synthesis (rings+elements) where flexible sources of narrow-spectrum/pitched noise are musically useful for excitation.)

**Comment by thomassidor** [comment]
I think if I just increase the frequency spectrum available in SN1 and SN8 then it should do what you need - right?

This is basically what it gives you:

![Capture](https://user-images.githubusercontent.com/56384979/67590576-b9a20b00-f75b-11e9-8952-f5c3a0c74fe6.JPG)

Around what rate of change would you need?

The module above is already done, but VCV Rack needs to update the library before it's available from there (unless you just download the release - v1.2.0 - here from Github and install it manually).

**Comment by glocke01** [comment]
SN1 and SN8 are now in my library! woohoo!

Ideally, I'd like to get up to around 500Hz. If it gets up to 50-100Hz, then wavefolding can function as a sort of frequency multiplier. Above 1kHz, linear interpolated S&H noise is good enough for my purposes.

**Comment by glocke01** [comment]
the fundamental RANDOM module goes up to ~2kHz, which is probably good enough for me. Also, using simplex noise for FM gets me a lot of what I want. 

Thanks again for your hard work and lovely modules!!
