### ISSUE TITLE
Why A4?

### ISSUE THREAD

**Issue by jeremywen** [thomassidor/tinytricks#9]
I want to use your oscillators but I would have to tune them every time.  Instead of tuning to C4 like most oscillators yours are tuned to A4.  Why is this?

**Comment by thomassidor** [comment]
Hi Jeremy

The honest answer is that I haven't given it much thought. The first code examples I looked at when I started the development used this base, so I just stuck with it.

But you're right - it would probably be much more useful if C4 is the base. I'll update it with 1.3.0 which should be out in a few days (including a new Simplex Noise based oscillator).

Thanks for the feedback - very much appreciated!

**Comment by jeremywen** [comment]
Ok sounds good, thank you!

**Comment by thomassidor** [comment]
The change have been released in v1.3.0

Currently waiting review and build update in VCV library.

Clossing ticket.
